apiVersion: v2
name: backend
version: 0.7.1
description: Backend of the Snoty application suite
type: application
home: https://snoty.me
sources:
  - https://github.com/SnotyMe/helm
  - https://github.com/SnotyMe/snoty-backend
maintainers:
  - name: Jakob Hofer
    email: contact@snoty.me
    url: https://github.com/SIMULATAN
icon: https://avatars.githubusercontent.com/u/163506575
appVersion: "0.6.1"
dependencies:
  - name: common
    version: 2.x.x
    repository: oci://registry-1.docker.io/bitnamicharts
  - name: mongodb
    version: ~16.4.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mongodb.deploy
  - name: keycloak
    version: 24.4.6
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: keycloak.deploy

