apiVersion: v2
name: backend
version: 0.2.1
description: Backend of the Snoty application suite
type: application
home: https://snoty.me
sources:
  - https://github.com/SnotyMe/helm
  - https://github.com/SnotyMe/snoty-backend
maintainers:
  - name: Jakob Hofer
    email: SIMULATAN@proton.me
    url: https://github.com/SIMULATAN
icon: https://avatars.githubusercontent.com/u/163506575
appVersion: "0.0.1-176"
dependencies:
  - name: common
    version: 2.x.x
    repository: oci://registry-1.docker.io/bitnamicharts
  - name: mongodb
    version: ~15.6.19
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.deploy
  - name: keycloak
    version: 22.1.2
    repository: https://charts.bitnami.com/bitnami
    condition: keycloak.deploy

